name: deployment

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  packer:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set packer version
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.7.10

      - name: Packer build
        run: |
          packer build -machine-readable --var-file=ami.pkrvars.hcl ami.pkr.hcl

      - name: Upload packer output file
        uses: actions/upload-artifact@v2
        with:
          name: packer.manifest.json
          path: packer.manifest.json

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
        
        
