name: packer

on:
  pull_request:
    branches: [main]

jobs:
  validate-packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set packer version
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.7.10
      
      - name: Create fake jar file to validate
        run: |
          mkdir target
          touch target/webapp-0.0.1-SNAPSHOT.jar

      - name: Packer validation
        run: packer validate ami.pkr.hcl
